(function(e){var h=window.AmazonUIPageJS||window.P,t=h._namespace||h.attributeErrors,c=t?t("AmazonGatewayHerotatorJS"):h;c.guardFatal?c.guardFatal(e)(c,window):c.execute(function(){e(c,window)})})(function(e,h,t){e.when("generic-observable").register("gw-herotator-controller",function(c){var m=function(){};return function(e){function k(){q.notifyObservers("delayBegin")}function l(){q.notifyObservers("delayInterrupted")}function g(a){for(var b=0;b<z.length;b++)if(z[b]===a)return b+1}function a(a){a=
a||{};return{delay_complete:a.delay_complete||m,js_ready:a.js_ready||m,fg_loaded:a.fg_loaded||m,mouse_move:a.mouse_move||m,mouse_leave:a.mouse_leave||m,delay_interrupted_timeout:a.delay_interrupted_timeout||m,rotation_complete:a.rotation_complete||m,goto_card:function(a){a!==B&&n.user_navigation(z[a-1])},user_navigation:a.user_navigation||function(a){n=new r(a)},user_interaction:a.user_interaction||function(){n.user_navigation(z[B-1])},stop_autorotation:a.stop_autorotation||function(){n.user_navigation(z[B-
1])},pause:a.pause||m,resume:a.resume||m}}function d(){function b(){!c&&C[d]&&(n=1===E?new A:new v)}k();var d=z[(B-1+1)%E+1-1],c=!0;return new a({fg_loaded:function(a){a===d&&b()},delay_complete:function(){c=!1;b()},mouse_move:function(){n=new f},pause:function(){n=new h}})}function f(){l();return new a({mouse_move:l,mouse_leave:function(){n=new d},delay_interrupted_timeout:function(){n.mouse_leave()},pause:function(){n=new h(!0)}})}function h(b){l();return new a({mouse_move:function(){b=!0;l()},
mouse_leave:function(){b=!1},resume:function(){n=b?new f:0<H?new d:new A}})}function v(){q.notifyObservers("autorotating");B=(B-1+1)%E+1;q.notifyObservers("gotoCard",B);H--;return new a({rotation_complete:function(){n=0<H?new d:new A},mouse_move:function(){n=0<H?new b:new A},pause:function(){n=new y}})}function b(b){var d=!1;return new a({rotation_complete:function(){k();n=d?new h:new f},pause:function(){d=!0},resume:function(){d=!1}})}function y(){var b=!1;return new a({rotation_complete:function(){k();
n=new h(b)},mouse_move:function(){b=!0},mouse_leave:function(){b=!1}})}function r(b){q.notifyObservers("userNavigation");B=g(b);q.notifyObservers("gotoCard",B);return new a({rotation_complete:function(){n=new A},user_navigation:function(a){n=new x(a)},user_interaction:m})}function x(b){return new a({rotation_complete:function(){n=new r(b)},user_navigation:function(a){b=a},user_interaction:m})}function A(){q.notifyObservers("stopAutorotation");return new a({})}e=e||{};var q=new c,n=new function(){function b(){C[D]&&
c&&(q.notifyObservers("ready"),n=new d,g&&n.pause(),f&&n.stop_autorotation())}var c=!1,f=!1,g=!1;return new a({fg_loaded:function(a){a===D&&b()},js_ready:function(){c=!0;b()},user_navigation:m,stop_autorotation:function(){f=!0},pause:function(){g=!0},resume:function(){g=!1}})},z=e.fgIDs||[],E=z.length,D=z[0],B=e.card_num||1,C={},H=e.circular?Infinity:E;return{delayComplete:function(){n.delay_complete()},jsReady:function(){n.js_ready()},fgLoaded:function(a){C[a]=!0;D===a&&q.notifyObservers("atfLoaded");
n.fg_loaded(a)},mouseMove:function(){n.mouse_move()},mouseLeave:function(){n.mouse_leave()},delayInterruptedTimeout:function(){n.delay_interrupted_timeout()},rotationComplete:function(){n.rotation_complete()},gotoCard:function(a){n.goto_card(a)},userInteraction:function(){n.user_interaction()},userNavigation:function(a){n.user_navigation(a)},stopAutorotation:function(){n.stop_autorotation()},pause:function(){n.pause()},resume:function(){n.resume()},addObserver:q.addObserver,removeObserver:q.removeObserver}}});
e.when("herotator-btf").register("herotator",function(c){return c});e.register("herotator-btf",function(){return function(c,m){function p(a){return function(){e.when("gw-desktop-herotator/controller").execute(function(){F[a]()})}}function k(a,b,n){a.addEventListener?a.addEventListener(b,n,!1):a.attachEvent("on"+b,n)}function l(a,n){E[a]=[];var d=n.length;if(0<d)for(var c=0;c<d;c++)(function(d){var c=new Image;c.onload=function(){E[a].splice(b(E[a],c),1);E[a]&&0===E[a].length&&
e.when("gw-desktop-herotator/controller").execute(function(){var b=document.getElementById("gw-ftGr-"+a),n=b.className,n=n.replace(/\s*\ba\-lazy\-loaded\b\s*/,"");b.className=n;F.fgLoaded(a)});e.when("A").execute(function(b){var n=b.$("#gw-ftGr-"+a+" img.a-dynamic-image");b.loadDynamicImage(n)})};E[a].push(c);c.src=n[d].src})(c);else e.when("gw-desktop-herotator/controller").execute(function(){F.fgLoaded(a)})}function g(){z=Date.now()}function a(){C||u()}function d(){I=I?Math.min(I,Date.now()):Date.now();
clearTimeout(q.timeout_id);clearTimeout(d.timeout_id);d.timeout_id=setTimeout(function(){d.timeout_id=0;F.delayInterruptedTimeout()},3E3)}function f(){C=!0}function u(){u.sent||(clearTimeout(u.timeout),u.timeout=setTimeout(function(){v(c.uri,c.data);u.sent=!0},2E3))}function v(a,b){e.when("A").execute(function(n){n.$.ajax(a,{async:!1,cache:!1,type:"post",data:b})})}function b(a,b){if(a.indexOf)return a.indexOf(b);for(var n=0;n<a.length;n++)if(a[n]===b)return n}function y(){return R=R||x()}function r(a){"object"===
typeof h.ue&&"function"===typeof h.ue.count&&h.ue.count(a,(h.ue.count(a)||0)+1)}function x(){var a=L(".a-carousel-rounded-buttons .a-carousel-left,.a-carousel-rounded-buttons .a-carousel-right");L(".a-carousel-rounded-buttons .a-carousel-left").attr("cel_widget_id","gw-desktop-hero-left-cel");L(".a-carousel-rounded-buttons .a-carousel-right").attr("cel_widget_id","gw-desktop-hero-right-cel");L(".a-carousel-rounded-buttons .a-carousel-left").addClass("celwidget");L(".a-carousel-rounded-buttons .a-carousel-right").addClass("celwidget");
L(".a-carousel-rounded-buttons .a-carousel-left").click(function(a){r("gw-desktop-hero-left")});L(".a-carousel-rounded-buttons .a-carousel-right").click(function(a){r("gw-desktop-hero-right")});return{show:function(){a.show();L(".a-carousel-left").css("z-index",10);L(".a-carousel-right").css("z-index",10)},hide:function(){a.hide()}}}function A(){var a=L("#gw-desktop-herotator");a.addClass("gw-desktop-herotator-ready");e.register("herotator-controls",function(){1<a.find(".a-carousel-card").length?
(y().show(),h.GWI&&h.GWI.recordLatency("gwHerotatorActive")):y().hide()})}function q(a){H<I&&(B-=I-H,I=0);H=Date.now();q.timeout_id=setTimeout(function(){B=D;F.delayComplete()},B)}function n(a,b){n.current_card!==b&&(n.current_card=b,w.gotoPage(b),T.notifyObservers("page_changed"));setTimeout(function(){F.rotationComplete()},250)}var z=Date.now(),E={},D=5E3,B=D,C=!1,H=0,I=0,w,L,K=document.getElementById("gw-desktop-herotator").getElementsByTagName("ol")[0],T,F,R;k(K,"click",p("userInteraction"));
k(K,"mouseenter",p("mouseMove"));k(K,"mousemove",p("mouseMove"));k(K,"mouseleave",p("mouseLeave"));k(K,"touchstart",p("userInteraction"));k(K,"touchmove",p("userInteraction"));k(K,"touchend",p("userInteraction"));k(K,"touchcancel",p("userInteraction"));for(var K=document.getElementById("gw-desktop-herotator").getElementsByTagName("li")[0],M=0,t=K.childNodes[M];t&&"div"!==String(t.nodeName).toLowerCase();)M++,t=K.childNodes[M];M=t;K=String(M.id).replace(/^gw-ftGr-/,"");M=M.getElementsByTagName("img");
l(K,M||[]);for(var N=[K],K=0;m[K];)N.push(m[K].fgID),K++;e.when("gw-herotator-controller").execute(function(b){F=new b({fgIDs:N});F.addObserver("atfLoaded",g);F.addObserver("delayBegin",q);F.addObserver("delayInterrupted",d);F.addObserver("gotoCard",n);F.addObserver("userNavigation",a);F.addObserver("stopAutorotation",f);F.addObserver("ready",function(){var a=Date.now()-z;B=Math.max(D-a,1);A();L("#gw-desktop-herotator").addClass("gw-desktop-herotator-ready")});e.register("gw-desktop-herotator/controller");
e.when("generic-observable").register("gw-desktop-herotator",function(a){T=new a;return{getAutorotationDelay:function(){return D},setAutorotationDelay:function(a){a=parseInt(a,10);B=a-(D-B);D=a},stopAutorotation:function(){F.stopAutorotation()},disableNavigation:function(){y().hide();w.pause()},enableNavigation:function(){y().show();w.resume()},pause:function(){F.pause()},resume:function(){F.resume()},addObserver:T.addObserver,removeObserver:T.removeObserver}})});e.when("A","a-carousel-framework",
"gwAjax").execute(function(a,b,n){function d(){var a=0;for(h.GWI&&h.GWI.recordLatency("gw-hero-btf-populate");m[a];){var b=m[a].fgID,n=m[a].content,c=document.getElementById("gw-ftGr-"+b);L(c).html(n);n=c.getElementsByTagName("img");l(b,n);a++}}L=a.$;b.onInit("gateway-desktop-layout.herotator",function(){var c=a.$("#gw-desktop-herotator > .a-carousel-container");w=b.getCarousel(c);w.onChange("pageNumber",function(){var a=w.getAttr("pageNumber");F.gotoCard(a);a-=2;m[a]&&m[a].callbackUrl&&(n(m[a].callbackUrl,
{type:"POST",id:"desktop-herotator-btf-"+m[a].fgID}),delete m[a].callbackUrl)});d();e.when("gw-desktop-herotator").register("gw-desktop-herotator/dom-ready");e.when("gw-desktop-herotator/controller","gw-desktop-herotator").execute(function(){F.jsReady()})})})}})});